version: '3'
services:
  app:
    build: .
    ports:
      - "3000:3000"

  docs:
    image: swaggerapi/swagger-ui
    ports:
      - "80:8080"
    depends_on:
      - app
    environment:
      SWAGGER_JSON_URL: http://localhost:3000/docs